"""Auto-generated by Rapid Neural Designer compiler."""

import numpy as np

# --- Node 1: InputTensor ---
input_tensor_1_tensor = np.random.randint(0, 32000, (1, 32)) if 'int' == 'int' else np.random.randn(1, 32).astype(np.float32)

# --- Node 2: TriangularMask ---
triangular_mask_2_mask = np.tril(np.ones((32, 32), dtype=np.float32))

# --- Node 3: Embedding ---
_emb3_table = np.random.randn(32000, 288).astype(np.float32) * 0.02
embedding_3_embeddings = _emb3_table[input_tensor_1_tensor]

# --- Node 4: Transformer Block 1 ---
# === Transformer Block 4 ===
_tb4_d = 288
_tb4_h = 6
_tb4_dk = _tb4_d // _tb4_h
_tb4_hd = 768
#
# -- Attention Norm --
_tb4_an_w = np.ones(_tb4_d, dtype=np.float32)
_tb4_normed = embedding_3_embeddings * (1.0 / np.sqrt(np.mean(embedding_3_embeddings ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb4_an_w
#
# -- RoPE Multi-Head Attention --
_tb4_wq = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wk = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wv = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wo = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_bs, _tb4_sl, _ = _tb4_normed.shape
_tb4_q = np.matmul(_tb4_normed, _tb4_wq.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_k = np.matmul(_tb4_normed, _tb4_wk.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_v = np.matmul(_tb4_normed, _tb4_wv.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb4_dk, 2, dtype=np.float32) / _tb4_dk))
_tb4_pos = np.arange(_tb4_sl, dtype=np.float32)
_tb4_ang = np.outer(_tb4_pos, _tb4_freqs)
_tb4_cos = np.cos(_tb4_ang).astype(np.float32)
_tb4_sin = np.sin(_tb4_ang).astype(np.float32)
_tb4_qr = np.zeros_like(_tb4_q)
_tb4_qr[..., 0::2] = _tb4_q[..., 0::2] * _tb4_cos - _tb4_q[..., 1::2] * _tb4_sin
_tb4_qr[..., 1::2] = _tb4_q[..., 0::2] * _tb4_sin + _tb4_q[..., 1::2] * _tb4_cos
_tb4_kr = np.zeros_like(_tb4_k)
_tb4_kr[..., 0::2] = _tb4_k[..., 0::2] * _tb4_cos - _tb4_k[..., 1::2] * _tb4_sin
_tb4_kr[..., 1::2] = _tb4_k[..., 0::2] * _tb4_sin + _tb4_k[..., 1::2] * _tb4_cos
_tb4_sc = np.matmul(_tb4_qr, _tb4_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb4_dk)
if triangular_mask_2_mask is not None:
    _tb4_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb4_sc)
_tb4_ex = np.exp(_tb4_sc - np.max(_tb4_sc, axis=-1, keepdims=True))
_tb4_aw = _tb4_ex / np.sum(_tb4_ex, axis=-1, keepdims=True)
_tb4_av = np.matmul(_tb4_aw, _tb4_v)
_tb4_attn_out = np.matmul(_tb4_av.transpose(0, 2, 1, 3).reshape(_tb4_bs, _tb4_sl, _tb4_d), _tb4_wo.T)
#
# -- Residual 1 --
_tb4_res1 = embedding_3_embeddings + _tb4_attn_out
#
# -- FFN Norm --
_tb4_fn_w = np.ones(_tb4_d, dtype=np.float32)
_tb4_fn = _tb4_res1 * (1.0 / np.sqrt(np.mean(_tb4_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb4_fn_w
#
# -- SwiGLU FFN --
_tb4_wg = np.random.randn(_tb4_hd, _tb4_d).astype(np.float32) * 0.02
_tb4_wu = np.random.randn(_tb4_hd, _tb4_d).astype(np.float32) * 0.02
_tb4_wd = np.random.randn(_tb4_d, _tb4_hd).astype(np.float32) * 0.02
_tb4_gate = np.matmul(_tb4_fn, _tb4_wg.T)
_tb4_up = np.matmul(_tb4_fn, _tb4_wu.T)
_tb4_silu = _tb4_gate * (1.0 / (1.0 + np.exp(-_tb4_gate)))
_tb4_ffn_out = np.matmul(_tb4_silu * _tb4_up, _tb4_wd.T)
#
# -- Residual 2 --
transformer_block_4_output = _tb4_res1 + _tb4_ffn_out

# --- Node 5: Transformer Block 2 ---
# === Transformer Block 5 ===
_tb5_d = 288
_tb5_h = 6
_tb5_dk = _tb5_d // _tb5_h
_tb5_hd = 768
#
# -- Attention Norm --
_tb5_an_w = np.ones(_tb5_d, dtype=np.float32)
_tb5_normed = transformer_block_4_output * (1.0 / np.sqrt(np.mean(transformer_block_4_output ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb5_an_w
#
# -- RoPE Multi-Head Attention --
_tb5_wq = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wk = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wv = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wo = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_bs, _tb5_sl, _ = _tb5_normed.shape
_tb5_q = np.matmul(_tb5_normed, _tb5_wq.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_k = np.matmul(_tb5_normed, _tb5_wk.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_v = np.matmul(_tb5_normed, _tb5_wv.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb5_dk, 2, dtype=np.float32) / _tb5_dk))
_tb5_pos = np.arange(_tb5_sl, dtype=np.float32)
_tb5_ang = np.outer(_tb5_pos, _tb5_freqs)
_tb5_cos = np.cos(_tb5_ang).astype(np.float32)
_tb5_sin = np.sin(_tb5_ang).astype(np.float32)
_tb5_qr = np.zeros_like(_tb5_q)
_tb5_qr[..., 0::2] = _tb5_q[..., 0::2] * _tb5_cos - _tb5_q[..., 1::2] * _tb5_sin
_tb5_qr[..., 1::2] = _tb5_q[..., 0::2] * _tb5_sin + _tb5_q[..., 1::2] * _tb5_cos
_tb5_kr = np.zeros_like(_tb5_k)
_tb5_kr[..., 0::2] = _tb5_k[..., 0::2] * _tb5_cos - _tb5_k[..., 1::2] * _tb5_sin
_tb5_kr[..., 1::2] = _tb5_k[..., 0::2] * _tb5_sin + _tb5_k[..., 1::2] * _tb5_cos
_tb5_sc = np.matmul(_tb5_qr, _tb5_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb5_dk)
if triangular_mask_2_mask is not None:
    _tb5_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb5_sc)
_tb5_ex = np.exp(_tb5_sc - np.max(_tb5_sc, axis=-1, keepdims=True))
_tb5_aw = _tb5_ex / np.sum(_tb5_ex, axis=-1, keepdims=True)
_tb5_av = np.matmul(_tb5_aw, _tb5_v)
_tb5_attn_out = np.matmul(_tb5_av.transpose(0, 2, 1, 3).reshape(_tb5_bs, _tb5_sl, _tb5_d), _tb5_wo.T)
#
# -- Residual 1 --
_tb5_res1 = transformer_block_4_output + _tb5_attn_out
#
# -- FFN Norm --
_tb5_fn_w = np.ones(_tb5_d, dtype=np.float32)
_tb5_fn = _tb5_res1 * (1.0 / np.sqrt(np.mean(_tb5_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb5_fn_w
#
# -- SwiGLU FFN --
_tb5_wg = np.random.randn(_tb5_hd, _tb5_d).astype(np.float32) * 0.02
_tb5_wu = np.random.randn(_tb5_hd, _tb5_d).astype(np.float32) * 0.02
_tb5_wd = np.random.randn(_tb5_d, _tb5_hd).astype(np.float32) * 0.02
_tb5_gate = np.matmul(_tb5_fn, _tb5_wg.T)
_tb5_up = np.matmul(_tb5_fn, _tb5_wu.T)
_tb5_silu = _tb5_gate * (1.0 / (1.0 + np.exp(-_tb5_gate)))
_tb5_ffn_out = np.matmul(_tb5_silu * _tb5_up, _tb5_wd.T)
#
# -- Residual 2 --
transformer_block_5_output = _tb5_res1 + _tb5_ffn_out

# --- Node 6: Transformer Block 3 ---
# === Transformer Block 6 ===
_tb6_d = 288
_tb6_h = 6
_tb6_dk = _tb6_d // _tb6_h
_tb6_hd = 768
#
# -- Attention Norm --
_tb6_an_w = np.ones(_tb6_d, dtype=np.float32)
_tb6_normed = transformer_block_5_output * (1.0 / np.sqrt(np.mean(transformer_block_5_output ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb6_an_w
#
# -- RoPE Multi-Head Attention --
_tb6_wq = np.random.randn(_tb6_d, _tb6_d).astype(np.float32) * 0.02
_tb6_wk = np.random.randn(_tb6_d, _tb6_d).astype(np.float32) * 0.02
_tb6_wv = np.random.randn(_tb6_d, _tb6_d).astype(np.float32) * 0.02
_tb6_wo = np.random.randn(_tb6_d, _tb6_d).astype(np.float32) * 0.02
_tb6_bs, _tb6_sl, _ = _tb6_normed.shape
_tb6_q = np.matmul(_tb6_normed, _tb6_wq.T).reshape(_tb6_bs, _tb6_sl, _tb6_h, _tb6_dk).transpose(0, 2, 1, 3)
_tb6_k = np.matmul(_tb6_normed, _tb6_wk.T).reshape(_tb6_bs, _tb6_sl, _tb6_h, _tb6_dk).transpose(0, 2, 1, 3)
_tb6_v = np.matmul(_tb6_normed, _tb6_wv.T).reshape(_tb6_bs, _tb6_sl, _tb6_h, _tb6_dk).transpose(0, 2, 1, 3)
_tb6_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb6_dk, 2, dtype=np.float32) / _tb6_dk))
_tb6_pos = np.arange(_tb6_sl, dtype=np.float32)
_tb6_ang = np.outer(_tb6_pos, _tb6_freqs)
_tb6_cos = np.cos(_tb6_ang).astype(np.float32)
_tb6_sin = np.sin(_tb6_ang).astype(np.float32)
_tb6_qr = np.zeros_like(_tb6_q)
_tb6_qr[..., 0::2] = _tb6_q[..., 0::2] * _tb6_cos - _tb6_q[..., 1::2] * _tb6_sin
_tb6_qr[..., 1::2] = _tb6_q[..., 0::2] * _tb6_sin + _tb6_q[..., 1::2] * _tb6_cos
_tb6_kr = np.zeros_like(_tb6_k)
_tb6_kr[..., 0::2] = _tb6_k[..., 0::2] * _tb6_cos - _tb6_k[..., 1::2] * _tb6_sin
_tb6_kr[..., 1::2] = _tb6_k[..., 0::2] * _tb6_sin + _tb6_k[..., 1::2] * _tb6_cos
_tb6_sc = np.matmul(_tb6_qr, _tb6_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb6_dk)
if triangular_mask_2_mask is not None:
    _tb6_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb6_sc)
_tb6_ex = np.exp(_tb6_sc - np.max(_tb6_sc, axis=-1, keepdims=True))
_tb6_aw = _tb6_ex / np.sum(_tb6_ex, axis=-1, keepdims=True)
_tb6_av = np.matmul(_tb6_aw, _tb6_v)
_tb6_attn_out = np.matmul(_tb6_av.transpose(0, 2, 1, 3).reshape(_tb6_bs, _tb6_sl, _tb6_d), _tb6_wo.T)
#
# -- Residual 1 --
_tb6_res1 = transformer_block_5_output + _tb6_attn_out
#
# -- FFN Norm --
_tb6_fn_w = np.ones(_tb6_d, dtype=np.float32)
_tb6_fn = _tb6_res1 * (1.0 / np.sqrt(np.mean(_tb6_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb6_fn_w
#
# -- SwiGLU FFN --
_tb6_wg = np.random.randn(_tb6_hd, _tb6_d).astype(np.float32) * 0.02
_tb6_wu = np.random.randn(_tb6_hd, _tb6_d).astype(np.float32) * 0.02
_tb6_wd = np.random.randn(_tb6_d, _tb6_hd).astype(np.float32) * 0.02
_tb6_gate = np.matmul(_tb6_fn, _tb6_wg.T)
_tb6_up = np.matmul(_tb6_fn, _tb6_wu.T)
_tb6_silu = _tb6_gate * (1.0 / (1.0 + np.exp(-_tb6_gate)))
_tb6_ffn_out = np.matmul(_tb6_silu * _tb6_up, _tb6_wd.T)
#
# -- Residual 2 --
transformer_block_6_output = _tb6_res1 + _tb6_ffn_out

# --- Node 7: Transformer Block 4 ---
# === Transformer Block 7 ===
_tb7_d = 288
_tb7_h = 6
_tb7_dk = _tb7_d // _tb7_h
_tb7_hd = 768
#
# -- Attention Norm --
_tb7_an_w = np.ones(_tb7_d, dtype=np.float32)
_tb7_normed = transformer_block_6_output * (1.0 / np.sqrt(np.mean(transformer_block_6_output ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb7_an_w
#
# -- RoPE Multi-Head Attention --
_tb7_wq = np.random.randn(_tb7_d, _tb7_d).astype(np.float32) * 0.02
_tb7_wk = np.random.randn(_tb7_d, _tb7_d).astype(np.float32) * 0.02
_tb7_wv = np.random.randn(_tb7_d, _tb7_d).astype(np.float32) * 0.02
_tb7_wo = np.random.randn(_tb7_d, _tb7_d).astype(np.float32) * 0.02
_tb7_bs, _tb7_sl, _ = _tb7_normed.shape
_tb7_q = np.matmul(_tb7_normed, _tb7_wq.T).reshape(_tb7_bs, _tb7_sl, _tb7_h, _tb7_dk).transpose(0, 2, 1, 3)
_tb7_k = np.matmul(_tb7_normed, _tb7_wk.T).reshape(_tb7_bs, _tb7_sl, _tb7_h, _tb7_dk).transpose(0, 2, 1, 3)
_tb7_v = np.matmul(_tb7_normed, _tb7_wv.T).reshape(_tb7_bs, _tb7_sl, _tb7_h, _tb7_dk).transpose(0, 2, 1, 3)
_tb7_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb7_dk, 2, dtype=np.float32) / _tb7_dk))
_tb7_pos = np.arange(_tb7_sl, dtype=np.float32)
_tb7_ang = np.outer(_tb7_pos, _tb7_freqs)
_tb7_cos = np.cos(_tb7_ang).astype(np.float32)
_tb7_sin = np.sin(_tb7_ang).astype(np.float32)
_tb7_qr = np.zeros_like(_tb7_q)
_tb7_qr[..., 0::2] = _tb7_q[..., 0::2] * _tb7_cos - _tb7_q[..., 1::2] * _tb7_sin
_tb7_qr[..., 1::2] = _tb7_q[..., 0::2] * _tb7_sin + _tb7_q[..., 1::2] * _tb7_cos
_tb7_kr = np.zeros_like(_tb7_k)
_tb7_kr[..., 0::2] = _tb7_k[..., 0::2] * _tb7_cos - _tb7_k[..., 1::2] * _tb7_sin
_tb7_kr[..., 1::2] = _tb7_k[..., 0::2] * _tb7_sin + _tb7_k[..., 1::2] * _tb7_cos
_tb7_sc = np.matmul(_tb7_qr, _tb7_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb7_dk)
if triangular_mask_2_mask is not None:
    _tb7_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb7_sc)
_tb7_ex = np.exp(_tb7_sc - np.max(_tb7_sc, axis=-1, keepdims=True))
_tb7_aw = _tb7_ex / np.sum(_tb7_ex, axis=-1, keepdims=True)
_tb7_av = np.matmul(_tb7_aw, _tb7_v)
_tb7_attn_out = np.matmul(_tb7_av.transpose(0, 2, 1, 3).reshape(_tb7_bs, _tb7_sl, _tb7_d), _tb7_wo.T)
#
# -- Residual 1 --
_tb7_res1 = transformer_block_6_output + _tb7_attn_out
#
# -- FFN Norm --
_tb7_fn_w = np.ones(_tb7_d, dtype=np.float32)
_tb7_fn = _tb7_res1 * (1.0 / np.sqrt(np.mean(_tb7_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb7_fn_w
#
# -- SwiGLU FFN --
_tb7_wg = np.random.randn(_tb7_hd, _tb7_d).astype(np.float32) * 0.02
_tb7_wu = np.random.randn(_tb7_hd, _tb7_d).astype(np.float32) * 0.02
_tb7_wd = np.random.randn(_tb7_d, _tb7_hd).astype(np.float32) * 0.02
_tb7_gate = np.matmul(_tb7_fn, _tb7_wg.T)
_tb7_up = np.matmul(_tb7_fn, _tb7_wu.T)
_tb7_silu = _tb7_gate * (1.0 / (1.0 + np.exp(-_tb7_gate)))
_tb7_ffn_out = np.matmul(_tb7_silu * _tb7_up, _tb7_wd.T)
#
# -- Residual 2 --
transformer_block_7_output = _tb7_res1 + _tb7_ffn_out

# --- Node 8: RMSNorm ---
_rms8_weight = np.ones(288, dtype=np.float32)
_rms8_var = np.mean(transformer_block_7_output ** 2, axis=-1, keepdims=True)
rmsnorm_8_output = transformer_block_7_output * (1.0 / np.sqrt(_rms8_var + 1e-06)) * _rms8_weight

# --- Node 9: Output Projection ---
_w9 = np.random.randn(32000, 288).astype(np.float32) * 0.02
linear_9_output = np.matmul(rmsnorm_8_output, _w9.T)
if False:
    _b9 = np.zeros(32000, dtype=np.float32)
    linear_9_output = linear_9_output + _b9

# --- Node 10: Output ---
logits = linear_9_output
print(f'logits shape: { linear_9_output.shape}')
