# Generated by Rapid Neural Designer
# 2026-03-18T00:00:00.000Z

import numpy as np

# [InputTensor] node:1
input_tensor_1_tensor = np.random.randint(0, 32000, (1, 32)) if 'int' == 'int' else np.random.randn(1, 32).astype(np.float32)

# [TriangularMask] node:2
triangular_mask_2_mask = np.tril(np.ones((32, 32), dtype=np.float32))

# [Embedding] node:3
_emb3_table = np.random.randn(32000, 288).astype(np.float32) * 0.02
embedding_3_embeddings = _emb3_table[input_tensor_1_tensor]

# [Transformer Block] node:4
# === Transformer Block 4 ===
_tb4_d = 288
_tb4_h = 6
_tb4_dk = _tb4_d // _tb4_h
_tb4_hd = 768
#
# -- Attention Norm --
_tb4_an_w = np.ones(_tb4_d, dtype=np.float32)
_tb4_normed = embedding_3_embeddings * (1.0 / np.sqrt(np.mean(embedding_3_embeddings ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb4_an_w
#
# -- RoPE Multi-Head Attention --
_tb4_wq = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wk = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wv = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_wo = np.random.randn(_tb4_d, _tb4_d).astype(np.float32) * 0.02
_tb4_bs, _tb4_sl, _ = _tb4_normed.shape
_tb4_q = np.matmul(_tb4_normed, _tb4_wq.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_k = np.matmul(_tb4_normed, _tb4_wk.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_v = np.matmul(_tb4_normed, _tb4_wv.T).reshape(_tb4_bs, _tb4_sl, _tb4_h, _tb4_dk).transpose(0, 2, 1, 3)
_tb4_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb4_dk, 2, dtype=np.float32) / _tb4_dk))
_tb4_pos = np.arange(_tb4_sl, dtype=np.float32)
_tb4_ang = np.outer(_tb4_pos, _tb4_freqs)
_tb4_cos = np.cos(_tb4_ang).astype(np.float32)
_tb4_sin = np.sin(_tb4_ang).astype(np.float32)
_tb4_qr = np.zeros_like(_tb4_q)
_tb4_qr[..., 0::2] = _tb4_q[..., 0::2] * _tb4_cos - _tb4_q[..., 1::2] * _tb4_sin
_tb4_qr[..., 1::2] = _tb4_q[..., 0::2] * _tb4_sin + _tb4_q[..., 1::2] * _tb4_cos
_tb4_kr = np.zeros_like(_tb4_k)
_tb4_kr[..., 0::2] = _tb4_k[..., 0::2] * _tb4_cos - _tb4_k[..., 1::2] * _tb4_sin
_tb4_kr[..., 1::2] = _tb4_k[..., 0::2] * _tb4_sin + _tb4_k[..., 1::2] * _tb4_cos
_tb4_sc = np.matmul(_tb4_qr, _tb4_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb4_dk)
if triangular_mask_2_mask is not None:
    _tb4_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb4_sc)
_tb4_ex = np.exp(_tb4_sc - np.max(_tb4_sc, axis=-1, keepdims=True))
_tb4_aw = _tb4_ex / np.sum(_tb4_ex, axis=-1, keepdims=True)
_tb4_av = np.matmul(_tb4_aw, _tb4_v)
_tb4_attn_out = np.matmul(_tb4_av.transpose(0, 2, 1, 3).reshape(_tb4_bs, _tb4_sl, _tb4_d), _tb4_wo.T)
#
# -- Residual 1 --
_tb4_res1 = embedding_3_embeddings + _tb4_attn_out
#
# -- FFN Norm --
_tb4_fn_w = np.ones(_tb4_d, dtype=np.float32)
_tb4_fn = _tb4_res1 * (1.0 / np.sqrt(np.mean(_tb4_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb4_fn_w
#
# -- SwiGLU FFN --
_tb4_wg = np.random.randn(_tb4_hd, _tb4_d).astype(np.float32) * 0.02
_tb4_wu = np.random.randn(_tb4_hd, _tb4_d).astype(np.float32) * 0.02
_tb4_wd = np.random.randn(_tb4_d, _tb4_hd).astype(np.float32) * 0.02
_tb4_gate = np.matmul(_tb4_fn, _tb4_wg.T)
_tb4_up = np.matmul(_tb4_fn, _tb4_wu.T)
_tb4_silu = _tb4_gate * (1.0 / (1.0 + np.exp(-_tb4_gate)))
_tb4_ffn_out = np.matmul(_tb4_silu * _tb4_up, _tb4_wd.T)
#
# -- Residual 2 --
transformer_block_4_output = _tb4_res1 + _tb4_ffn_out

# [Transformer Block] node:5
# === Transformer Block 5 ===
_tb5_d = 288
_tb5_h = 6
_tb5_dk = _tb5_d // _tb5_h
_tb5_hd = 768
#
# -- Attention Norm --
_tb5_an_w = np.ones(_tb5_d, dtype=np.float32)
_tb5_normed = transformer_block_4_output * (1.0 / np.sqrt(np.mean(transformer_block_4_output ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb5_an_w
#
# -- RoPE Multi-Head Attention --
_tb5_wq = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wk = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wv = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_wo = np.random.randn(_tb5_d, _tb5_d).astype(np.float32) * 0.02
_tb5_bs, _tb5_sl, _ = _tb5_normed.shape
_tb5_q = np.matmul(_tb5_normed, _tb5_wq.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_k = np.matmul(_tb5_normed, _tb5_wk.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_v = np.matmul(_tb5_normed, _tb5_wv.T).reshape(_tb5_bs, _tb5_sl, _tb5_h, _tb5_dk).transpose(0, 2, 1, 3)
_tb5_freqs = 1.0 / (10000.0 ** (np.arange(0, _tb5_dk, 2, dtype=np.float32) / _tb5_dk))
_tb5_pos = np.arange(_tb5_sl, dtype=np.float32)
_tb5_ang = np.outer(_tb5_pos, _tb5_freqs)
_tb5_cos = np.cos(_tb5_ang).astype(np.float32)
_tb5_sin = np.sin(_tb5_ang).astype(np.float32)
_tb5_qr = np.zeros_like(_tb5_q)
_tb5_qr[..., 0::2] = _tb5_q[..., 0::2] * _tb5_cos - _tb5_q[..., 1::2] * _tb5_sin
_tb5_qr[..., 1::2] = _tb5_q[..., 0::2] * _tb5_sin + _tb5_q[..., 1::2] * _tb5_cos
_tb5_kr = np.zeros_like(_tb5_k)
_tb5_kr[..., 0::2] = _tb5_k[..., 0::2] * _tb5_cos - _tb5_k[..., 1::2] * _tb5_sin
_tb5_kr[..., 1::2] = _tb5_k[..., 0::2] * _tb5_sin + _tb5_k[..., 1::2] * _tb5_cos
_tb5_sc = np.matmul(_tb5_qr, _tb5_kr.transpose(0, 1, 3, 2)) / np.sqrt(_tb5_dk)
if triangular_mask_2_mask is not None:
    _tb5_sc = np.where(triangular_mask_2_mask == 0, -1e9, _tb5_sc)
_tb5_ex = np.exp(_tb5_sc - np.max(_tb5_sc, axis=-1, keepdims=True))
_tb5_aw = _tb5_ex / np.sum(_tb5_ex, axis=-1, keepdims=True)
_tb5_av = np.matmul(_tb5_aw, _tb5_v)
_tb5_attn_out = np.matmul(_tb5_av.transpose(0, 2, 1, 3).reshape(_tb5_bs, _tb5_sl, _tb5_d), _tb5_wo.T)
#
# -- Residual 1 --
_tb5_res1 = transformer_block_4_output + _tb5_attn_out
#
# -- FFN Norm --
_tb5_fn_w = np.ones(_tb5_d, dtype=np.float32)
_tb5_fn = _tb5_res1 * (1.0 / np.sqrt(np.mean(_tb5_res1 ** 2, axis=-1, keepdims=True) + 1e-06)) * _tb5_fn_w
#
# -- SwiGLU FFN --
_tb5_wg = np.random.randn(_tb5_hd, _tb5_d).astype(np.float32) * 0.02
_tb5_wu = np.random.randn(_tb5_hd, _tb5_d).astype(np.float32) * 0.02
_tb5_wd = np.random.randn(_tb5_d, _tb5_hd).astype(np.float32) * 0.02
_tb5_gate = np.matmul(_tb5_fn, _tb5_wg.T)
_tb5_up = np.matmul(_tb5_fn, _tb5_wu.T)
_tb5_silu = _tb5_gate * (1.0 / (1.0 + np.exp(-_tb5_gate)))
_tb5_ffn_out = np.matmul(_tb5_silu * _tb5_up, _tb5_wd.T)
#
# -- Residual 2 --
transformer_block_5_output = _tb5_res1 + _tb5_ffn_out

# [RMSNorm] node:6
_rms6_weight = np.ones(288, dtype=np.float32)
_rms6_var = np.mean(transformer_block_5_output ** 2, axis=-1, keepdims=True)
rmsnorm_6_output = transformer_block_5_output * (1.0 / np.sqrt(_rms6_var + 1e-06)) * _rms6_weight

# [Linear] node:7
_w7 = np.random.randn(32000, 288).astype(np.float32) * 0.02
linear_7_output = np.matmul(rmsnorm_6_output, _w7.T)
if False:
    _b7 = np.zeros(32000, dtype=np.float32)
    linear_7_output = linear_7_output + _b7

print(f"Output shape: {linear_7_output.shape}")
print("Model execution complete.")
