#!/usr/bin/env python3
"""Test code generation without torch dependency"""

import requests

test_code = """# Neural VM Experiment: simple_test
# Generated by Neural VM Builder

import numpy as np

print("Testing code generation...")
print("NumPy version:", np.__version__)

# Simple array operations
x = np.random.randn(1, 10, 512) * 0.1
print(f"Created tensor of shape: {x.shape}")
print(f"Mean: {x.mean():.4f}, Std: {x.std():.4f}")

print("Experiment 'simple_test' completed successfully!")
"""

print("=" * 60)
print("Testing Code Generation (No Torch)")
print("=" * 60)

try:
    response = requests.post(
        'http://localhost:5000/execute',
        json={'code': test_code},
        timeout=60
    )

    result = response.json()

    if result.get('success'):
        print("\n[SUCCESS] Code executed successfully!")
        print(f"Execution time: {result.get('execution_time')}s")
        if result.get('stdout'):
            print(f"\nOutput:\n{result.get('stdout')}")
    else:
        print("\n[FAILED] Execution failed!")
        print(f"Error: {result.get('error', 'Unknown error')}")
        if result.get('stderr'):
            print(f"\nStderr:\n{result.get('stderr')}")

except Exception as e:
    print(f"[ERROR] {e}")